### ISSUE TITLE
Support for Varnish 5?

### ISSUE THREAD

**Issue by craigcarnell** [claranet/puppet-varnish#30]

**Comment by wschoot** [comment]
Would like this too, as 3 and 4 are EOL.

**Comment by MWilkinson** [comment]
Hi @craigcarnell, @wschoot 
we also needed this - I've raised a PR #36 which updated the package repo to use packagecloud's repository and also includes support for Varnish version 5.x

**Comment by craigwatson** [comment]
@MWilkinson thanks for your PR, it has now been merged :)
