### ISSUE TITLE
Support for IPv6 or multiple listen addresses

### ISSUE THREAD

**Issue by Rikbruggink** [claranet/puppet-varnish#33]
Hi,

Currently the module has no support for ipv6 or multiple listen addresses. Ideal this would de implemented as a array in daemon options or as new config variable varnish.params

**Comment by craigwatson** [comment]
Hi,

Thanks for raising this, the functionality has now been added to the `sysvinit` and `systemd` ERB templates in commit a6daadcdbfc201c3b30cf2adc70fc5655d645642.

Thanks,
Craig
