### ISSUE TITLE
Debian 8 doesn't use systemd

### ISSUE THREAD

**Issue by rodricels** [claranet/puppet-varnish#50]
With a Debian Jessie, the module use sysvinit instead of systemd.

Puppet says that $::lsbdistrelease (8) is lower than 8.0: `versioncmp(8, 8.0) == -1`

https://github.com/claranet/puppet-varnish/blob/7ea6aa1704a78d45655b1811af4ddec7f3dd8982/manifests/params.pp#L41-L57

Pull request #51

**Comment by craigwatson** [comment]
Fixed by #51
