### ISSUE TITLE
Fixing deprecation issues

### ISSUE THREAD

**Issue by lessevv** [claranet/puppet-varnish#53]
Currently, Puppet is throwing deprecation errors when using the Varnish module on Puppet 5. The Varnish module is still using, for example, validate_string, which has been deprecated.

**Comment by ralfbosz** [comment]
https://github.com/claranet/puppet-varnish/commit/3d3af11511ce177a3ebd3a19e71f70b1c61735dd

**Comment by craigwatson** [comment]
Thanks and apologies for the delay in getting this released - version 5.0.0 has been released to the Forge! :)
