### ISSUE TITLE
puppetlabs/apt old

### ISSUE THREAD

**Issue by zogot** [claranet/puppet-varnish#62]
Hello,

It appears that while you define support for stdlib < 6.0 your current version of puppetlabs/apt is at < 5.0 which resolves in the latest of 4.5.1 https://forge.puppet.com/puppetlabs/apt/4.5.1/dependencies which has stdlib at < 5.0 meaning I currently can't use it with my other dependencies. 

Is there any hope on getting this updated to the latest puppetlabs/apt?

**Comment by lelutin** [comment]
I'd also like to see this bumped. This module is currently the only one holding us back from upgrading puppetlabs/apt and we'd very much like to do so soon.
