### ISSUE TITLE
systemd file on Debian Buster not working

### ISSUE THREAD

**Issue by Kotty666** [claranet/puppet-varnish#65]
My Configuration:

varnish::addrepo: false
varnish::listen:
  - ':80
else are defaults.

The Systemd-Service file is generated with an "\" at the end of the Service section, this breaks the Startup of the varnish service with:
Oct 17 08:03:19 web01p varnishd[16430]: Error: Too many arguments ([Install]...)
Oct 17 08:03:19 web01p varnishd[16430]: (-? gives usage)

[varnish.service.txt](https://github.com/claranet/puppet-varnish/files/3738162/varnish.service.txt)

**Comment by NITEMAN** [comment]
This should be open until #74 lands
